name: CD
on:
  push:
    branches:
      - main
jobs:
  increment_version:
    name: Increment Version
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: "yarn"

      - name: Release action
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CI: true
        run: yarn release

  release_version:
    name: Release version
    runs-on: ubuntu-latest
    needs: increment_version
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - run: git pull

      - uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: "yarn"

      - name: Extract tag version
        id: tag_version
        run: |
          export TAG_VERSION=$(node -p "require('./package.json').version")
          echo "::set-output name=tag_version::$TAG_VERSION"

      - name: Print tag version
        run: echo ${{ steps.tag_version.outputs.tag_version }}

      - name: Build action
        run: yarn build

      - name: Create tag version
        uses: JasonEtco/build-and-tag-action@v2
        with:
          tag_name: v${{ steps.tag_version.outputs.tag_version }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Reset tag version to latest commit
        run: |
          git tag --force v${{ steps.tag_version.outputs.tag_version }}
          git push --force --tags
