name: CI

on: [ pull_request ]


jobs:
  install_deps:
    name: Install dependencies
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=yarn-cache-dir::$(yarn cache dir)"

      - name: Cache yarn cache
        uses: actions/cache@v2
        id: cache-yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.yarn-cache-dir }}
          key: ${{ runner.os }}-build-${{ env.cache-yarn-cache }}-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-yarn-cache }}
      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          path: node_modules
          key: ${{ runner.os }}-build-${{ env.cache-name }}-v0-${{ hashFiles('**/yarn.lock') }}

      - name: Install Dependencies
        run: yarn install --frozen-lockfile --prefer-offline

  test:
    name: Run tests
    runs-on: ubuntu-latest
    needs: [ install_deps ]
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          path: node_modules
          key: ${{ runner.os }}-build-${{ env.cache-name }}-v0-${{ hashFiles('**/yarn.lock') }}

      - name: Run tests
        run: yarn test


  run_the_action:
    name: Run actual action
    runs-on: ubuntu-latest
    needs: [ install_deps ]
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: '12'

      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          path: node_modules
          key: ${{ runner.os }}-build-${{ env.cache-name }}-v0-${{ hashFiles('**/yarn.lock') }}

      - name: Build action
        run: yarn build

      - name: Run action with default UTC timezone
        uses: ./
        continue-on-error: true

      - name: Run action with CET timezone
        uses: ./
        continue-on-error: true
        with:
          timezone: CET

      - name: Run action with Europe/London timezone
        uses: ./
        continue-on-error: true
        with:
          timezone: Europe/London
